### ISSUE TITLE
Allow using custom close function / command

### ISSUE THREAD

**Issue by famiu** [akinsho/nvim-bufferline.lua#106]
So as you might already know, the default `:bdelete` command in Neovim is quite annoying in the sense that it messed up the window layouts. I made a function that bypasses it and would want to be able to configure nvim-bufferline to use it instead of `:bdelete` or whatever else it uses for deleting that buffer. So it would be really nice to have that option.

**Comment by akinsho** [comment]
@famiu yes this would be good to add, I'm beginning to get very wary of new features since at the rate at which I'm accepting user requests for new configuration options I think this plugin will have like 50 in 6 months so I'm planning on being quite strict now. This one though is I think quite a sensible thing that I'm surprised no one asked for earlier although tbh I almost never close buffers with the mouse 😄 .

So I'm actually not a 100% sure how to do this but it should be possible. The main reason is that the click functionality works by specifying a viml function to call in the tabline string, this is called with some specific arguments it just calls bufferline's lua handlers.

The issue is how to pass the config in to the handler.
https://github.com/akinsho/nvim-bufferline.lua/blob/9f65bb79ddf9e888b01c1d685692fd5c3e4ab16a/lua/bufferline.lua#L715
In hindsight I should have made the config module have a getter and setter rather than passing config all over the place, but this was my first lua plugin so didn't know any better.

Anyway the solution would be to do something like that so that in the function I linked to above you could simply do
`config.get('close_command')` and use that value if a `function` then run it otherwise pass it to `vim.cmd`

Anyway not sure when I'll get to it myself so a PR would be very welcome 🙏🏾 otherwise will leave this here till I'm able to get round to it.

**Comment by famiu** [comment]
@akinsho If I make a PR, would you mind if I, along with allowing to add custom functions, also added built-in integration with [bufdelete.nvim](https://github.com/famiu/bufdelete.nvim), which is basically the code I wrote but I decided to turn it into a plugin?

**Comment by akinsho** [comment]
@famiu a PR would be fantastic 🙏🏾 , with regards to an integration tbh I've tried very hard (not sure if I'm winning) to make this plugin kind of lightweight. I mean from a UI standpoint it's definitely not minimal but it doesn't get involved with how users manage their buffers and I'd like to keep that separation i.e. this plugin shows you your buffers in cool/nice looking ways with more scope for stuff like groupings in the future but it shouldn't manage them really.

I'd be fine with an example in the README of showing how it could be used generally and how it could be used with something like `bufdelete.nvim` and even link to that plugin but I wouldn't want this plugin to explicitly *know* about any other plugins unless there becomes a lot of user demand, but I think I'm more at risk of adding too much stuff and scaring people away than of adding too little.

**Comment by famiu** [comment]
I see that's fine, I'll try making a PR if I get the time to soon 👍🏼

**Comment by akinsho** [comment]
@famiu this should be much easier to do now that I've create a `config.get` method you can now just create a key in the config, and inside of the function I use before do `config.get().options.close_command` and then check the type and use it
