### ISSUE TITLE
Changing background of unselected buffer doesn't work

### ISSUE THREAD

**Issue by astier** [akinsho/nvim-bufferline.lua#11]
In the following minimal vimrc I am trying to change every background to red. It works for some backgrounds like for the selected buffer and the tabs but not for the unselected buffers:

```vim
set runtimepath+=~/.local/share/nvim/plugins/nvim-bufferline.lua/
set termguicolors
lua require'bufferline'.setup {
\    highlights = {
\        bufferline_tab = {
\            guibg = "red",
\        };
\        bufferline_tab_selected = {
\            guibg = "red",
\        };
\        bufferline_buffer = {
\            guibg = "red",
\        };
\        bufferline_buffer_inactive = {
\            guibg = "red",
\        };
\        bufferline_modified = {
\            guibg = "red",
\        };
\        bufferline_separator = {
\            guibg = "red",
\        };
\        bufferline_selected = {
\            guibg = "red",
\        };
\    },
\}
```

**Comment by akinsho** [comment]
@astier sorry won't have time to look at this for a couple of days. Tbh I added the configuration options as an after thought and so haven't really ensured that they all work. I could be that the name in the code is different than in the README. It might be a good idea to look in `bufferline.lua` to see if the name matches. 

Long term I'm not really sure how much customisation of colours I'm going to support so I'd take all color overriding options to be in alpha atm, since I might rename these variables or remove the ones that are too tricky to allow users to override

**Comment by astier** [comment]
Ok no problem. Its not that important. I will take at the `bufferline.lua` ;)

**Comment by cooper-anderson** [comment]
Highly doubt this is still an ongoing problem, but it looks like ever since commit https://github.com/akinsho/nvim-bufferline.lua/commit/8a66060e7dad55abd9de0d5488062fd809b0f3d9 setting the highlights no longer requires the `bufferline_` prefix. 👍

**Comment by akinsho** [comment]
Yep this issue isn't relevant anymore I thanks for mentioning. I'll close this out and if something similar recurs we can open a new issue 👍🏿
