### ISSUE TITLE
can't offset buffers over 'undotree'

### ISSUE THREAD

**Issue by foundObjects** [akinsho/nvim-bufferline.lua#113]
Hey there, I'm not sure if I'm doing something wrong here or if this is a bug but I'm unable to offset the bufferline over an 'undotree' plugin sidebar window. The relevant section of my bufferline config starts with something like this:

```
require('bufferline').setup {
    options = {
        offsets = {
            {filetype = "NvimTree", text = "Explorer"},
            {filetype = "undotree", text = "Undo"}
        },
```

And the filetype from the undotree window reports 'undotree' when I run `echo &ft` from it. The offset functions correctly over NvimTree, just not undotree.

I'm using the undotree plugin here: https://github.com/mbbill/undotree

Thoughts?

**Comment by akinsho** [comment]
@foundObjects this is a known limitation of the offset feature. It only works with *full height* side bar panel windows. It works by using `winlayout` to see if the window the user specified a file type for is a full height one since the number of possible window layouts in nvim is huge, it just does the simplest thing. In `undotree`'s case it creates two windows so technically it isn't a full heigh panel.

Potentially I could add in more logic to check if it's a top level window i.e. just under the bufferline and use that to determine if it should show the offset but tbh when the user who requested this functionality asked for it I clarified that I would avoid going down a complexity rabbit hole myself for it.

If someone else wants to look into it 
The expected layout required for this to work currently is
`{ "row", {{ "leaf", 1004 }, { "leaf", 1005 }}`

but with undotree it looks like
`{ "row", { { "col", { { "leaf", 1004 }, { "leaf", 1005 } } }, { "leaf", 1000 } } }`
so rather than 2 leaf windows there is a column of 2 windows `1004` and `1005` so the check
https://github.com/akinsho/nvim-bufferline.lua/blob/fbafdf3c3974e6fb1fa97afa314af7a6cffee3f4/lua/bufferline/offset.lua#L84
doesn't work for this layout.

**Comment by RaZ0rr-Two** [comment]
One workaround for this problem is to put the following settings somewhere it is `source`d or `require`d

```
" auto open diff window
if !exists('g:undotree_DiffAutoOpen')
    let g:undotree_DiffAutoOpen = 0
endif
```

The diff panel can then be toggled manually with D. One another usual complimentary settting for this is:

" if set, let undotree window get focus after being opened, otherwise

```
        " focus will stay in current window.
        if !exists('g:undotree_SetFocusWhenToggle')
                  let g:undotree_SetFocusWhenToggle = 1  
        endif
```

**Comment by foundObjects** [comment]
> @foundObjects this is a known limitation of the offset feature. It only works with _full height_ side bar panel windows. It works by using `winlayout` to see if the window the user specified a file type for is a full height one since the number of possible window layouts in nvim is huge, it just does the simplest thing. In `undotree`'s case it creates two windows so technically it isn't a full heigh panel.
> 
> Potentially I could add in more logic to check if it's a top level window i.e. just under the bufferline and use that to determine if it should show the offset but tbh when the user who requested this functionality asked for it I clarified that I would avoid going down a complexity rabbit hole myself for it.
> 
> If someone else wants to look into it
> The expected layout required for this to work currently is
> `{ "row", {{ "leaf", 1004 }, { "leaf", 1005 }}`
> 
> but with undotree it looks like
> `{ "row", { { "col", { { "leaf", 1004 }, { "leaf", 1005 } } }, { "leaf", 1000 } } }`
> so rather than 2 leaf windows there is a column of 2 windows `1004` and `1005` so the check
> https://github.com/akinsho/nvim-bufferline.lua/blob/fbafdf3c3974e6fb1fa97afa314af7a6cffee3f4/lua/bufferline/offset.lua#L84
> 
> 
> doesn't work for this layout.

Thanks for the explanation! I'm not terribly proficient in lua yet but I'll look at implementing this when I've got some time and see if I can get somewhere. I agree that the infinite possible layouts makes this annoying to tackle, personally I'd be totally fine with peeking into the layout and looking for only top level windows in each column as overlay anchors. 



> One workaround for this problem is to put the following settings somewhere it is `source`d ( or `require`d if converted to lua with `vim.g`)
> 
> ```
> " auto open diff window
> if !exists('g:undotree_DiffAutoOpen')
>     let g:undotree_DiffAutoOpen = 0
> endif
> ```
> 
> The diff panel can then be toggled manually with the `D` key. One another usual complimentary settting for this is:
> 
> ```
> " if set, let undotree window get focus after being opened, otherwise
> " focus will stay in current window.
> if !exists('g:undotree_SetFocusWhenToggle')
>   let g:undotree_SetFocusWhenToggle = 1  
> endif
> ```

This is also helpful, thanks!

**Comment by rockyzhang24** [comment]
Hi @akinsho

Is this limitation resolved? I tried but it still didn't work. 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11582667/159054136-252de64b-7dd8-42e5-ba7a-608e3c1e46a9.png">

Thank you very much.

**Comment by akinsho** [comment]
@rockyzhang24 the problem is solved but depends on how you open undo tree in my case the diff buffer is contained inside the split on the left whereas on yours it's at the bottom, in either case it should work. If it doesn't, and you've made sure you're on the latest version, then I'd try with other layouts, i.e. the default undotree layout and see if that works. I don't personally intend to spend more time on this feature, though, as it was a user request that spiralled out into a bunch  more work than I'd have wanted. Open to PRs if you find some bug and want to contribute a fix

**Comment by rockyzhang24** [comment]
@akinsho Thank you. I tried different layouts and it works for layout style 1 (i.e., diff buffer is contained inside the split on the left). However, it doesn't work for layout style 2 (i.e., diff buffer is at the bottom). I am sure I am on the latest version for both `bufferline` and `undotree`. It's weird.

**Comment by akinsho** [comment]
@rockyzhang24 it's not really weird, just how the functionality works. It was designed almost explicitly for a single file explorer type pane which was the original user feature request and most people's use case, but others have expanded it to a load of different scenarios, but the solution is not applicable to all scenarios. They way it works is by reading the state of nvim's windows and figuring out if there is a left or right aligned vertical space that matches the filetype passed in. The way this information is returned from nvim means that there are a lot of different configurations for a given screen, and so the plugin only looks at the simplest versions that match the intended layout. I personally as I mentioned am not going to try and make it work for every layout since this is a lot of work that I personally don't feel is necessary.
