### ISSUE TITLE
Support for more closing commands

### ISSUE THREAD

**Issue by sahilsehwag** [akinsho/nvim-bufferline.lua#122]
It would be great, if we can have support for additional close commands

- Close all buffers
- Close all buffers to the left
- Close all buffers to the right
- Close all buffers besides current one

**Comment by akinsho** [comment]
Hi @sahilsehwag,

So I'm in two minds about this, one sort of tenet I have for this plugin is that it doesn't manage a users buffers, it just shows them in a nice way and there's quite a lot of scope to change the way they are shown. This kind of moves things more in the direction of managing things since it involves adding commands to handle buffer deletion and then inevitably things like, should it close them if modified should ignore certain types etc.

I'd be open to reviewing a PR for this but I think I'd only merge the *left* and *right* functionality since the last one `close all but the current` has a native command for it already called `:only` and `close all buffers` will close vim unless that's supposed to also create a new empty buffer in which case that really does seem like a buffer managing plugin like `bufdelete.nvim`'s job.

The left and right one though specifically relate to what the bufferline shows the user and can only really be implemented here so I'm more open to those.

I'm currently focusing more on other projects rather than new features for this plugin atm so if someone wants to contribute that would be appreciated.

**Comment by sahilsehwag** [comment]
I agree the first and the fourth can be done using native vim functionality(although close is not the correct option for this, since its a window command and not a buffer command). But It would be great if you can implement the close all left close to the right command.

**Comment by akinsho** [comment]
@sahilsehwag I wasn't referring to the close command, but either way regarding implementation as a pointed out I'm not currently working on new features. I'll leave this open in case yourself or someone else decides to implement this. I can provide some advice on how to do it since I don't think it would be particularly difficult.

**Comment by akinsho** [comment]
Fixed by #124
