### ISSUE TITLE
Feature Request: Additional Mappings to move between buffer

### ISSUE THREAD

**Issue by tami5** [akinsho/nvim-bufferline.lua#13]
Hey @akinsho , thanks a lot for this awesome plugin, I've got the chance to try it while building my neovim configuration from scratch with lua. I like how responsive and well made it is.

If it possible and absolutely easy to accomplish
- Additional mappings to switch between buffers like bn and bp within the current tab only. 
- Show only buff tabs for current buffer only.

The reason that this might be a great feature for nvim-bufferline.lua users, is that it would give users the ability to have a workspace like experience when working with buffers. Each tab can have its own buffer where navigation happens only between them. 

Thanks

**Comment by akinsho** [comment]
@tami5 thanks for the kind words 👍🏿 

I actually thought about this a lot when I first implemented this plugin. I had a look at some prior art like [wintabs](https://github.com/zefei/vim-wintabs) and reading around more generally. My conclusion from what I saw is that given that vim does not support this natively. It would require basically implementing a whole layer on top of vim for interacting with tabs and buffers. I'd need to hook into all buffer and tab creation to make sure things lined up as well as manually curating the relationship of buffers to tabs since vim has no native concept of a relationship between the two.

Also this plugin would have to stray into the territory of creating buffer and tab navigation commands and mappings that maintained/worked with this idea of buffers per tab.

Ultimately I think it would be too much of a deviation from how nvim actually works and a lot of logic to try to get it to behave in a way which it wasn't built for. I think it would be much better if nvim supported the idea of buffers scoped to a tab but that seems very unlikely to actually happen.

**Comment by tami5** [comment]
Oh thats unfortunate that neovim doesn't  support such a thing, I appreciate explaining  why this would be very complicated to implement and is originally was explicitly defined as some thing out-of-scope for nvim-bufferline.lua. 

Thank you
