### ISSUE TITLE
[feature request] Close neovim with last buffer

### ISSUE THREAD

**Issue by rgnkn** [akinsho/nvim-bufferline.lua#139]
Hello everyone,

maybe I'm missing something, but I don't see any way to close the running neovim when I close (clicking) the last open buffer.

Apologize me if I oversaw any options to apply this or if you suggest implementing this functionality outside nvim-bufferline. Any suggestions are welcome.

BTW, thanks for your fantastic plugin.

**Comment by akinsho** [comment]
Hi @rgnkn, so this plugin doesn't offer this functionality. You can override the click behaviour to implement this yourself by passing it a function to check if the buffer is the last one and close nvim if it is, otherwise just delete the buffer. I don't think I will add this to the plugin itself since there is already a way to do this, and I don't really like the idea of a bufferline UI plugin closing neovim by itself, I personally feel like it should never do that.

**Comment by rgnkn** [comment]
Thanks for your reply, I will stick to your suggestion. Therefore I will close this issue.

Have a nice day.
