### ISSUE TITLE
user highlights not set after startup refactor

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#142]
Hi @akinsho , I updated the plugin today and my highlights looked different from before 

before :

![image](https://user-images.githubusercontent.com/59060246/125648322-19803437-3e1e-4111-9e3e-2be2f1a6f669.png)

after : 

![image](https://user-images.githubusercontent.com/59060246/125648395-3dc4fa38-82fd-40d8-8243-28ad84c41260.png)

have the highlight groups changed or such?

**Comment by akinsho** [comment]
@siduck76 nope, no groups have changed. I did refactor the plugin to delay processing the user config till after startup. How are your highlights set? do they use an autocommand or are you doing lazy loading or something?

**Comment by akinsho** [comment]
I just did a quick test and highlights set during the setup call should all still work, not sure what might be going on in your config but a default setup should work as far as I can see.

**Comment by siduck76** [comment]
> @siduck76 nope, no groups have changed. I did refactor the plugin to delay processing the user config till after startup. How are your highlights set? do they use an autocommand or are you doing lazy loading or something?

I set separated the hightlights from the plugin so I load bufferline config first then a highlights.lua file which has bufferline highlights , I set highlights like this : 

hi BufferLineFill guifg="#etc"

**Comment by siduck76** [comment]
my config : https://github.com/siduck76/NvChad/blob/main/lua/plugins/bufferline.lua

the way I highlight bufferline stuff : https://github.com/siduck76/NvChad/blob/main/lua/highlights.lua#L105

**Comment by Mofiqul** [comment]
I am also having the same issue 
[My config](https://gist.github.com/Mofiqul/24435c3cabf7b39669677df10106325c)

**Comment by akinsho** [comment]
@siduck76 In your case, the reason this is probably happening is that you are overwriting the bufferline highlights directly, which btw isn't a good way to configure the plugin. It's better to put the highlights you want to change directly into the setup call for this plugin that way when it starts up it will apply your colours. The reason you are probably having this issue is that even though it *looks* like your highlights are being set after bufferline, bufferline now waits till vim enter to add its highlights, so it's actually adding the highlights after your overrides.

**Comment by akinsho** [comment]
@Mofiqul can you give some more specifics about what exactly you are seeing, e.g. what highlights aren't loading, and what parts of your config control when bufferline is loaded? Are you using autocommands etc? The example config you show in your gist works for me, so it is likely as with Siduck an ordering issue

**Comment by Mofiqul** [comment]
@akinsho  Its `buffer_visible` is not loading and I also notice `:luafile $MYVIMRC` works as expected but not at startup

**Comment by akinsho** [comment]
Ok I can reproduce the `bufferline_visible` issue, that's pretty strange since all the other highlights are working. I'll take a look

**Comment by siduck76** [comment]
@akinsho bufferline hides if there's just one buffer , how do I disable that?

**Comment by akinsho** [comment]
@siduck76 that isn't a default setting did you disable `always_show_bufferline`?

**Comment by akinsho** [comment]
@Mofiqul I spoke too soon, I just re-tested, and I can't reproduce the issue (wasn't actually testing with a visible buffer 😄). When I apply highlights to buffer visible, they work in my config. Can you please clarify how you are loading bufferline? And how highlights are being setup in your config. All the highlights work in the same way, so I'm not sure why only one group wouldn't work.

**Comment by siduck76** [comment]
@akinsho it works now , https://github.com/siduck76/NvChad/blob/main/lua/plugins/bufferline.lua#L23 . But I think adding the highlights in the setup call looks messy :(

**Comment by akinsho** [comment]
@siduck76 I think that is definitely a matter of personal preference, I personally don't see why a lua table is more messy than a bunch of function calls 🤷🏿‍♂️.

More important than (perceived) messiness is the design of this plugin, it is intended that the user should give the plugin a table representing their highlight preferences so that I can use those colours easily programmatically rather than relying on exposed highlight groups that nvim can do all sorts of things to. The user's highlights table is the source of truth, the highlights aren't even exposed publicly to prevent anyone from trying to manipulate those directly.

The way you had it setup before would almost certainly break at some point in the future because if you rely on those directly then I have no way of changing or deprecating a highlight or renaming it without breaking the user's config.

You could technically have made it work using an autocommand for `VimEnter` +/- `ColorScheme` but like I said that is not supported.

**Comment by siduck76** [comment]
@akinsho actually thanks , I had lazy loaded almost all the plugins . And bufferline actually showed up among the slowest 5 plugins (startuptime.vim , it took 0.150 ms ~) , now it no longer shows as the slowest plugin after adding the highlights in the setupcall itself :D

![image](https://user-images.githubusercontent.com/59060246/125786428-e8077ddb-2ff6-415c-94ef-b6873e64f51a.png)

**Comment by LuisxSullivaN** [comment]
@akinsho don't you think this prevents colorschemes from supporting this plugin? we'd have to manually set the colors.

**Comment by akinsho** [comment]
@LuisxSullivaN one of the core reasons I created this plugin was that I wanted a bufferline that was *consistent* regardless of colorscheme. I didn't want myself or users to add a new colorscheme only to be like why is the focused tab suddenly purple or why are the close buttons bright red or something. I want this plugin to work very similarly across themes i.e. use the same highlight groups per theme.

Unfortunately or unmanageably colorscheme authors have found the highlight groups this plugin uses and are overriding them exactly the way that I didn't intend. Tbh I would much rather that they just ensured that all the expected highlights existed an didn't try to change them in their themes.

All of which is a bit of a side note from the main issue here because the plugin defers loading till startup it is hard for colorschemes to change the colors (which as I've covered is not intended or designed for anyway) the best way to use the plugin is to see how it behaves out of the box and *then* if you the user want to change a few groups you do it yourself by adding your overrides to the setup object so this colorscheme can use *only the config* as the source of truth.
