### ISSUE TITLE
show buffers of active tab only

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#154]
Hi @akinsho! loving bufferline very much so far :D . I wanted to know if its possible to show buffers list of  current tab only? 

like ( by default there is only 1 tab )

- open a  "x" file 

- open a new tab ( this is tab 2 then)  and switch to it

- open a "y" file 

I want to see only x file's buffer which was opened in tab 1 and y file's buffer which was opened in tab 2 and not mix all the buffers of other tabs too.

**Comment by akinsho** [comment]
@siduck76 since this sounds like the beginning of an attempt to make tabs work like workspaces I'm going to just start with a warning which is that *tabs are not workspaces*. This comes up a lot in vim circles because people try and make them behave that way a lot but that's not what they are. Any buffer open in any tab is *not specific to that tab* a buffer can appear in 5 different tabs it's not specific.

That being said, you can do something like this with the `custom_filter` key I'll show you a non-functional example, you have to work out how to get it working for your use case yourself.

```lua
  local function custom_filter(buf, buf_nums)
    -- get the current tab page number
    local current_tab = vim.api.nvim_get_current_tabpage()
    -- get a list of buffers for a specific tab
	local tab_buffers = vim.fn.tabpagebuflist(current_tab)
    -- check if the current buffer is being viewed in the current tab
	return vim.tbl_contains(tab_buffers, buf)
  end
```
Please note this snippet is *untested* you will probably need to tweak it yourself to get it to work

**Comment by akinsho** [comment]
@siduck76 can I close this now?

**Comment by joehannes** [comment]
the above snippet didn't work for me, as it shows currently visible buffers only.
the following snippets helps me to show all buffers in the current working dir.
as you can set a different cwd per tabpage, I found this very helpful, as I can open different projects in different tabs and it will filter me and show only buffers that belong to the current project (if i set the cwd):

```lua
require("bufferline").setup({ options = {
	custom_filter = function(buf_number)
		if not not vim.api.nvim_buf_get_name(buf_number):find(vim.fn.getcwd(), 0, true) then
			return true
		end
	end,
}})
```
