### ISSUE TITLE
Ignore terminal buffer in bufferline

### ISSUE THREAD

**Issue by glepnir** [akinsho/nvim-bufferline.lua#16]
I make a floatwindow to show some command in terminal. It always show in bufferline when I close this floatwindow.

**Comment by akinsho** [comment]
@glepnir I don't want this plugin to special case buffer handling. The best way to handle not wanting a buffer to show up I think is to `setlocal nobuflisted`. Bufferline will omit any unlisted buffers. I think this is better because sometimes e.g. floating windows I want to be hidden but also sometimes I'm running tests in a terminal and I want to be able to see the buffer in my bufferline

**Comment by glepnir** [comment]
No..like this gif.  I create a floatwindow to show lazygit. then I close it. It still in bufferline. 
![after](https://user-images.githubusercontent.com/41671631/96973632-be55f680-154a-11eb-808d-4bd2e11df6a7.gif)



This is strange behavior. Sometimes I call the terminal just to execute the command, and I don’t want to see it again.
Maybe provide an option for the user to control whether to display the terminal buffer

**Comment by akinsho** [comment]
@glepnir what happens if you run `:ls` in that situation. I've never seen this behaviour before and I think it points to an issue with the state of the buffer maybe. Rather than adding another option I  think it would be good to investigate why that buffer is appearing in your bufferline at all. Is it from a plugin? I uses `fzf` in a float, `lazygit.nvim` in a float etc. and none of these show up in the bufferline. If it's a custom function are you setting the buffer to be *unlisted*?

**Comment by akinsho** [comment]
Alternatively you can go into the command line when that buffer is open and run `:echo &buflisted` to see if its `1` or `0`

**Comment by glepnir** [comment]
I don't use any plugin. it's my personal  window api written in lua. the result is 1.

**Comment by MohamedIrfanAM** [comment]
> I found problem. and solve it. thx.

Could you please explain how you did it ?? I have the same issue
