### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#165]
Can bufferline have animations like Barbar.nvim?

https://github.com/romgrk/barbar.nvim

**Comment by akinsho** [comment]
@siduck76 the short answer is, no.

A few things worth saying, I have no personal beef with barbar it's obviously very popular. The animations are also undoubtedly something a lot of people like about it. I'm personally perfectly fine with this plugin being less popular than it if it means I don't have to make choices that I don't support or that I don't feel are right.

The long answer is that I think trying to animate the bufferline is
* *Needlessly complex* - If you look through the commits that introduced animation in barbar it brought with it what is (to me anyway) a huge amount of complexity. Almost everything about the rendering in barbar is made much more complex by the animations. I haven't had a look in a long while though.

* *The animations aren't worth it/don't look very nice in TUI in this context* - this is another major sticking point for me. nvim (if not used in a GUI) is a *terminal program* I don't think this means there can't be animations, but I think the bufferline is a bad candidate for it. I've seen some cool things with floating windows and progress animations. The animations in barbar I personally feel aren't nice enough to warrant the complexity. I think bigger editors don't really animate their tab bars either, at least not that I've ever seen, and if they do, then always in a much sleeker way than I think can be achieved in a terminal. 

* *Just focus on the task at hand* - this is probably the most angry grandpa reason, I'm obviously a fan of making nice looking UI things for neovim, but I think there is a limit or a point beyond which things are just needlessly distracting. I personally think animating the tab bar even if it could be done isn't something I'd ever turn on, I like to think that all the visual flourishes that this plugin provides at least are all useful for doing your work i.e. you can see buffer numbers to close them or lsp diagnostics to see what errors are in buffers rather than flashy for it's own sake.

**Comment by siduck76** [comment]
@akinsho yes you are right , I didn't know it would be complex . Anyways the decoration api here ( sliding animation gif) looks so cool https://neovim.discourse.group/t/wip-animated-notifications-plugin/448  . But yeah if it adds more complexity,  then don't look onto it. I dont want one of my favorite nvim plugin's dev to stress about this thing :D

**Comment by siduck76** [comment]
Not related to this issue :

Can we group tabs? Like clicking one tab would open up a lil telescope pop-up or such and list all the tabs associated with that grouped tab . Ik this sounds complex , also we could group buffers the same way theoretically.
