### ISSUE TITLE
Current tab indicator broken with ayu-vim

### ISSUE THREAD

**Issue by ihasdapie** [akinsho/nvim-bufferline.lua#168]
I noticed that the current tab indicator highlight is broken when used with [ayu-vim](https://github.com/ayu-theme/ayu-vim)

![image](https://user-images.githubusercontent.com/54821716/127053775-8b1832d1-28a3-48e4-bdda-36cec8c4d9ea.png)

Not quite sure what the best way to fix this would be. If you can give me a pointer I'll submit a PR if that would help, but shouldn't be a really big fix.

Thanks!

**Comment by akinsho** [comment]
Hi @ihasdapie, so I don't tend to add fixes for specific color schemes to this plugin, it is supposed to be completely agnostic of color schemes. Looking at this particular issue, it seems to be because the `TabLineSel` highlight group is maybe not being set by `ayu`. See `:h hl-TabLineSel` for more info on this highlight. In either case, I think the right solution is to contribute a highlight for that group to that colorscheme

**Comment by ihasdapie** [comment]
I see, thanks for your input & the great plugin!
