### ISSUE TITLE
[Question] vim tab movement binds have weird behavior

### ISSUE THREAD

**Issue by milse113** [akinsho/nvim-bufferline.lua#172]
The vim binds `gt` and `gT` almost never behave as expected. Sometimes they don't work at all, other times they just completely skip tabs, sometimes it moved the cursor within a file (presumably moving to a duplicate buffer. No other errors or issues are visible.

**Comment by akinsho** [comment]
Hi @milse113,

so the `gt` and `gT` commands have very little to do with this plugin. Those mappings are for changing vim tabs and this plugin operates on vim buffers. Those commands will not move through bufferline buffers since they are not tabs. As you mention with the cursor a buffer in another tab is in another window so it won't share the cursor position with the previous window.

**Comment by milse113** [comment]
Well this plugin in effect replaces vim tabs, correct? Is there a way of emulating this behavior using bufferline?

**Comment by akinsho** [comment]
> Well this plugin in effect replaces vim tabs, correct?

This is not correct actually, this plugin shows a user *buffers* not tabs. It shows tab indicators which appear on the right side of the bufferline, so you can see that switching tabs will change the tab indicators, but the main focus of this plugin is buffers.

**Comment by milse113** [comment]
I see; is it possible to use this as a tab line then?

**Comment by akinsho** [comment]
@milse113 short answer is no, this has been asked quite few more times than I expected since I expected the name of the plugin would make things clear already.

Anyway I'll say to you what I've said to other people asking a similar question. My usecase and the reason I built this plugin is I want to see what files I have opened easily and to sort them/order them how I like. I don't personally understand why people what to see a list of tabs since tabs are just a collection of windows. I personally don't understand the use case at all.

That being said, I personally won't implement this functionality since as I mentioned I don't need it. If someone else like yourself wants to help implement this here then it is technically possible and I can provide some guidance, but I won't do it myself.
