### ISSUE TITLE
[Bug]: Abnormal Chinese display in the bufferline.

### ISSUE THREAD

**Issue by alohaia** [akinsho/nvim-bufferline.lua#177]
### What happened?

![截屏-20210808151940-980x1068](https://user-images.githubusercontent.com/36324537/128625014-818a6edb-dde2-4fdd-a0a1-fc22bba211dd.png)

### What did you expect to happen?

It's expected that the titles are displayed correctly.

### Additional Information

I'm not clear about the reason, but I guess that you may need the function `vim.fn.strwidth` which returns the size of string when displayed.

**Comment by akinsho** [comment]
@alohaia thanks for raising this issue. Can you please clarify what language you are using this plugin with? I actually already use `strwidth` in this plugin, this issue seems to be more about how the characters are being rendered, which this plugin doesn't actually control. I'm not sure based on the information you've provided, I can fix this.

Can you share a minimal init.lua and buffer name that will reproduce this issue?

**Comment by alohaia** [comment]
@akinsho

Minimal `init.lua`:

```lua
require('bufferline').setup{}
```

with only nvim-bufferline.lua installed under `~/.local/share/nvim/site/pack/packer/start`.

![image](https://user-images.githubusercontent.com/36324537/128699568-55e8600f-b658-4c1f-a440-3c815fdb1b8a.png)

The buffer name in this picture is `配子的发生与受精.md`. Hope these can help.

**Comment by akinsho** [comment]
@alohaia I just pushed a commit which I believe fixes this 9d8bf06. Can you let me know if that works for you?

**Comment by alohaia** [comment]
@akinsho strangely, it seemly only works for the buffer name `配子的发生与受精.md` and only when it's the first buffer. It failed to display correctly when I open other buffers:

![image](https://user-images.githubusercontent.com/36324537/128713267-6e2d265b-61f2-4a22-84fe-a21da5a7ffd4.png)

or open another buffer as the first buffer:

![image](https://user-images.githubusercontent.com/36324537/128713468-5551c0b1-439c-4a08-8a88-b2af88f6415b.png)

Here are some buffer names which I hope will help you debug: `主要组织相容性复合体.md`, `虫媒病毒和出血热病毒.md`, `Lua 迭代器和泛型 for.md`.

**Comment by akinsho** [comment]
@alohaia thanks the names are definitely helpful. I think the issue as I understand it now is that the plugin tries to measure the length of a buffer name and if it is longer than a certain width it will truncate the name and add an ellipsis. The issue is that using lua to truncate the buffer names using `string.sub` works at the byte level not the display cell level which is why it breaks I think. I'll dig in a bit more.

**Comment by akinsho** [comment]
Alright, just pushed another fix, please let me know if that resolves it. I tried all the filenames you provided, and they don't error any more. I don't think vim is counting the number of characters correctly but tbh I don't know how it should be done though tbh. `主要组织相容性复合体.md` looks like 13 charaters to me, but vim counts by cell, and it returns `20` for that string, so maybe it counts each character as 2. I'll defer to whatever vim does by default, since I won't implement that sort of complex multibyte character handling here.

**Comment by alohaia** [comment]
@akinsho Chinese characters are displayed in the width of two English characters here. That's why `vim.api.nvim_strwidth` counts each Chinese character as 2. As a result, it can not be used to judge whether the name is too long correctly and will cause extra trailing character `…`(showed in the picture below) when you truncate the buffer name in character count other than in display width. I suppose that `vim.fn.strchars` will be better.

![image](https://user-images.githubusercontent.com/36324537/128728155-a89a4158-5c51-45f8-b333-439a66a8814e.png)

**Comment by akinsho** [comment]
@alohaia I tried that, and it seems to work fine, except I don't know if it's correct since truncation should happen based on how many *cells* a character occupies, not based on the number of characters. The intent with the truncation is that it is checking against the width of the terminal grid, so truncation is based on the number of columns, not the actual character count.

Looking at the characters in my editor, they each occupy 2 cells, so I believe it is correct to truncate them since the equivalent number of cells in English would also be truncated.

![image](https://user-images.githubusercontent.com/22454918/128740657-90455ca1-916a-4a02-acae-b75117922ec2.png)


I guess it means that Chinese buffer names will look like they are aggressively truncated, but I think this is the expected behaviour and the maximum name length config option should be used instead, it's somewhat arbitrarily derived atm as 18, but a user can increase this to whatever they want.

**Comment by alohaia** [comment]
@akinsho yes, you're right. But the code seemly doesn't work as you expected.

![image](https://user-images.githubusercontent.com/36324537/128810193-0f3ee7bf-959f-4efb-b0a5-69f7d25b77f8.png)

https://github.com/akinsho/nvim-bufferline.lua/blob/5c82307c64143ed2848e6ea1777ee51a40d3b978/lua/bufferline.lua#L219-L232

The name `人类发育的细胞学和遗传学基础.md` has `17` characters and occupies `31` cells. It is judged to be too long by `api.nvim_strwidth` but isn't correctly truncated with `fn.strcharpart` because `fn.strcharpart` truncate string basing on character number. Is there a simple way to truncate Chinese buffer names correctly?

**Comment by akinsho** [comment]
@alohaia
> Is there a simple way to truncate Chinese buffer names correctly?

I have no idea, basically I want truncation to happen in terms of cells, but it appears it can't since each character has to be treated as a whole or else we are back to where we started, doing it by character alone is not a good solution since if there was a very large multibyte character things could start to overflow in an undesirable way.

I'll think a bit more about this, but open to suggestions from anyone who uses Chinese characters

**Comment by alohaia** [comment]
@akinsho if there is no other method provided, you can use the implementation `widestrpart` below. It's not that elegant, but it does work. You can use it in any way you like.

```lua
-- truncate str basing on number of columns
local function widestrpart(str, col_limit)
  while vim.fn.strwidth(str) > col_limit do
    str = fn.strcharpart(str, 0, vim.fn.strchars(str)-1)
  end
  return str
end


local function truncate_filename(filename, word_limit)
  local trunc_symbol = "…"
  if api.nvim_strwidth(filename) <= word_limit then
    return filename
  end
  -- truncate nicely by seeing if we can drop the extension first
  -- to make things fit if not then truncate abruptly
  local without_prefix = fn.fnamemodify(filename, ":t:r")
  if api.nvim_strwidth(without_prefix) < word_limit then
    return without_prefix .. trunc_symbol
  else
    -- return fn.strcharpart(filename, 0, word_limit - 1) .. trunc_symbol
    return widestrpart(filename, word_limit - 1) .. trunc_symbol
  end
end
```

**Comment by alohaia** [comment]
@akinsho sorry to respond so late because of the time difference. https://github.com/akinsho/nvim-bufferline.lua/pull/180#issue-707528849 fixes this issue perfectly, so I think it's time to close this issue.
