### ISSUE TITLE
[Question] Reload bufferline after theme or background change?

### ISSUE THREAD

**Issue by olimorris** [akinsho/nvim-bufferline.lua#181]
Firstly, loving `nvim-bufferline`. Recent convert from `barbar.nvim` and it's great!

One of my UI workflows consists of my whole Mac going dark before sunset. I have some nice Python scripts which cause my apps like Alacritty, Alfred, Code, Safari and Neovim, to switch to their respective dark modes.

For Neovim, I actually just apply a `vim.o.background = 'dark'` via the Neovim API. This causes my theme (for which I have dark and light color palettes) to adjust accordingly, but not bufferline:

![Screen Shot 2021-08-11 at 17 11 41@2x](https://user-images.githubusercontent.com/9512444/129065095-10e4c9c9-169e-41e6-a55a-79a134790bb2.png)

I have created some specific highlight groups in my theme which I apply in bufferline (a short excerpt is below):
```lua
highlights = {
        fill = {
            guibg = {
                attribute = "bg",
                highlight = "BufferlineFill"
            },
        },
        background = {
            guibg = {
                attribute = "bg",
                highlight = "BufferlineBg"
            }
        },
        -- Buffers
        buffer_selected = {
            guibg = {
                attribute = "bg",
                highlight = "BufferlineBufferSelected"
            },
            guifg = {
                attribute = "fg",
                highlight = "BufferlineBufferSelected"
            },
            gui = "bold"
        },
        buffer_visible = {
            guibg = {
                attribute = "bg",
                highlight = "BufferlineBufferVisible"
            },
            guifg = {
                attribute = "fg",
                highlight = "BufferlineBufferVisible"
            }
        }
}
```

Now when I restart Neovim, bufferline looks as intended. **It just doesn't automatically apply the new colors**. I did borrow a little lua function to try and reload the plugin but it doesn't seem to work:
```lua
-- utils.lua
local M = {}
M.reload_plugin = function(plugins)
    local status = true
    local function _reload_plugin(plugin)
        local loaded = package.loaded[plugin]
        if loaded then
            package.loaded[plugin] = nil
        end
        if not pcall(require, plugin) then
            print("Error: Cannot load " .. plugin .. " plugin!")
            status = false
        end
    end

    if type(plugins) == "string" then
        _reload_plugin(plugins)
    elseif type(plugins) == "table" then
        for _, plugin in ipairs(plugins) do
            _reload_plugin(plugin)
        end
    end
    return status
end

return M
```
...
```lua
local reload_plugin = require("utils").reload_plugin
reload_plugin("plugins.bufferline")
```

Curious if anyone else does something similar and has accomplished this?

**Comment by akinsho** [comment]
Hi @olimorris,

Thanks for the kind words.

So this should already work, i.e. changing the colorscheme should change for bufferline as well. If you swap between different colorschemes whilst vim is open, you should see this *with a minimal config* (I just verified locally).

I *think* in your case the reason this isn't working is that you have created some custom highlight groups and that is what bufferline is using when it refreshes. If those groups are also not setup to be automatically refreshed when your colorscheme changes, then that would explain the issue.

Can you try things with a minimal config, i.e. no custom colours and change colorschemes in nvim and see if bufferline adapts?

Then try changing background as well, this should trigger a colorscheme autocommand, there's a slim chance that somehow that might not be working.

Lastly, add your custom colors back and see if the issue recurs. If it does because of the custom colours, then you will need to make sure that those are recreated in a `Colorscheme` autocommand

**Comment by akinsho** [comment]
@olimorris to be clear, I don't think the solution to this has anything to do with bufferline. When you create a custom highlight then change your colorscheme, the colorscheme will clear all existing highlights in order to re-apply its own. You should always re-apply your custom highlights in a Colorscheme autocommand.

e.g.
```vim
function s:custom_hl()
	hi Color1 guifg=red
endfunction

augroup CustomHl
	au! Colorscheme * call s:custom_hl()
augroup END
```

**Comment by olimorris** [comment]
In the end I solved this by doing a little bit of refactoring of my own dotfiles. I create a color palette of light and dark colors. I then create an autocmd which which is bound to `ColorScheme` which reloads my bufferline setup and selects the correct color palette beforehand.

Really swish!

![Screen Shot 2021-08-16 at 16 51 09](https://user-images.githubusercontent.com/9512444/129592222-b97503e1-8d61-4ad7-83d0-b28a8dfcb3b0.gif)
