### ISSUE TITLE
[Feature request] Reorder buffers using mouse

### ISSUE THREAD

**Issue by ammmir** [akinsho/nvim-bufferline.lua#187]
It would be nice to be able to use the mouse to reorder tabs on the fly.

**Comment by akinsho** [comment]
@ammmir since neovim is a TUI program it doesn't support dragging and dropping (at least as far as I know), so I believe this request isn't even possible.

**Comment by ammmir** [comment]
thanks for the great plugin man!

"dragging and dropping" is essentially text selection in visual mode. not sure how it's implemented, but there is a tab plugin built-in to vim that supports reordering tabs by dragging the mouse. it's pretty cool.

on a fresh vim install run: `vim -p`
and then do a few `:tabnew` use the mouse to reorder the top tabs. you might need to enable mouse support first.

**Comment by akinsho** [comment]
Hmm, I never knew that existed as a feature of the default tabline. Tbh I have no idea how that works at all, and I can't find any documentation about it. If you happen to find clear implementation documentation that can serve as a jumping off point, then please post it here. I personally have a very mouseless workflow, so this won't be a priority for me to implement, but will definitely accept a PR or if you find any information on how that works that might make it easier to do, then we'll see. Otherwise, I'll leave this open on the "backlog"

**Comment by ammmir** [comment]
I perused `:help mouse` and came across some interesting tidbits, you can actually map stuff:

```
:map <S-LeftDrag>      <RightDrag>
:map <S-LeftRelease>   <RightRelease>
```

so if you map those 2 to functions that calculate the old tab position and new tab position, you can use `:tabmove` to perform the actual move. alas, I don't know the details about the mappings and callbacks, but seems possible?

**Comment by akinsho** [comment]
Hmm, I don't think that will work since the clickable functionality in the tabline uses the `tablineat` feature which allows passing a callback when creating the tabline string but it itself doesn't specify a way to handle drag actions. The mappings you link to would involve creating a global mapping overriding user settings and still wouldn't have access to the currently selected buffer tab whereas tabline at does.

**Comment by ammmir** [comment]
I started prototyping it:

```
map("n", "<LeftDrag>", ":lua require('utils').left_drag()<CR>", opt)
map("n", "<LeftRelease>", ":lua require('utils').left_release()<CR>", opt)
```

and then:

```lua
local is_dragging = false

function M.left_drag(a)
  if is_dragging == false then
    is_dragging = true
    print("start drag")
    -- todo: get source tab position under mouse
  end
end

function M.left_release()
  if is_dragging then
    is_dragging = false
    print("end drag")
    -- todo: get destination tab position under mouse
    -- todo: do the :tabmove 💃 
  end
end
```

**Comment by ammmir** [comment]
I think you're right. this is just overriding the global event handler. there doesn't seem to be a tree of event handler support in vim. I give up. I'll just get used to a keyboard.

**Comment by vypxl** [comment]
I stumbled upon this:
https://github.com/willothy/nvim-cokeline/pull/113

`nvim-cokeline` implemented it, is there a possibility to see this ported to bufferline?
