### ISSUE TITLE
[feature request]: Support to set custom area click callback function

### ISSUE THREAD

**Issue by xiyaowong** [akinsho/nvim-bufferline.lua#189]
![image](https://user-images.githubusercontent.com/47070852/130233302-55615d2f-369a-4230-b0a5-ce937d9bf6fd.png)

this is what I do now and It works well.  It would be nice if the plugin had direct support for registration callbacks

**Comment by akinsho** [comment]
@xiyaowong I don't think I will implement this because it will introduce unnecessary complexity in this plugin, meanwhile a user can already do this on their own. The idea with the custom area is that a user can go away and add some stuff of their own choosing and by default is intended for advanced users who are comfortable doing that, so I don't really plan on building in specific functionality with it in mind.

**Comment by xiyaowong** [comment]
I agree with you and thank you for your reply :)
