### ISSUE TITLE
[Question] How do I make shorten buffername if there are multiple buffers of the same name 

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#190]
Hi @akinsho ! Sorry for making another issue :( .I wanted to know if I could shorten the buffername's length if there are multiple buffers opened of the same name. For example : 

buffername with mksh 

![image](https://user-images.githubusercontent.com/59060246/130248406-b834fb67-8a4c-477b-b73b-9140242c90d8.png)

If there are multiple mksh buffers : 

![image](https://user-images.githubusercontent.com/59060246/130248459-b11fc4cb-1d52-480e-a279-a237a3516a81.png)

Cant we add just a single number on the left? like 

pid:/bin/mksh could be shown as  : 

mksh (1) or just add a superscript of number on mksh

**Comment by akinsho** [comment]
Hi @siduck76, short answer is no. The way buffers are deduplicated is that the plugin tries to find the first part of the buffer's path that is not the same as the other buffers of a similar name, so the length will be as long as that it takes to find the first different parent directory or the limit of a buffer name length. Tbh I will not change this myself. I don't like the idea of arbitrary numbers or other things like that, since to me that is meaningless, what does `mksh (1)` mean ? This is probably in this case an issue because of buffer terminals with the same command, which I don't think this plugin should have to work around.

You can use the `name_formatter` if you want to change how terminal plugins are rendered, but I'll leave you to read the docs on how to configure that.

**Comment by siduck76** [comment]
@akinsho I agree, thanks for mentioning the name_formatter , I'll definitely look onto it!

**Comment by akinsho** [comment]
Let me know if you get stuck @siduck76 sorry if I was a bit abrupt, getting quite a lot of issues/feature requests across my plugins. Didn't think they'd end up causing so much work for me in the end 😆

**Comment by siduck76** [comment]
> Let me know if you get stuck @siduck76 sorry if I was a bit abrupt, getting quite a lot of issues/feature requests across my plugins. Didn't think they'd end up causing so much work for me in the end

Haha np! I get issues everyday on my repo :rofl:
