### ISSUE TITLE
E5113: Error while calling lua chunk loop or previous error  loading module 'bufferline'

### ISSUE THREAD

**Issue by paradoxsupreme** [akinsho/nvim-bufferline.lua#36]
I get the following error when I try to add a lua file that contains the following `require'bufferline'.setup()` in order to load this plugin.
E5113: Error while calling lua chunk: /home/paradox_supreme/.config/nvim/lua/bufferline.lua:1: loop or previous error 
loading module 'bufferline'

**Comment by akinsho** [comment]
@paradoxsupreme thanks for trying out the plugin. I think this error is likely coming from neovim nightly sense there was a changed merged recently which affected how `require` works.

I've been seeing similar errors with the `lsp` there isn't really any logic or recent change that would have brought this on so that'd be my bet. Running the plugin myself I don't see this specific error. That being said if you can provide me with a minimal init.vim that reproduces this for you please post it here and I'll try it.

**Comment by paradoxsupreme** [comment]
> @paradoxsupreme thanks for trying out the plugin. I think this error is likely coming from neovim nightly since there was a change merged recently which affected how `require` works.
> 
> I've been seeing similar errors with the `lsp` there isn't really any logic or recent change that would have brought this on so that'd be my bet. Running the plugin myself I don't see this specific error. That being said if you can provide me with a minimal init.vim that reproduces this for you please post it here and I'll try it.

Hmm Ok I will try to see if I can find where the error is coming from then. I'll close this for now then and if the problem continues I will post an init.vim. Thanks!
