### ISSUE TITLE
[Bug]: Close buttons not working properly

### ISSUE THREAD

**Issue by MordechaiHadad** [akinsho/nvim-bufferline.lua#428]
### What happened?

OS: WSL Arch Linux.
Terminal: Windows Terminal
Bufferline Versions: `dev` `main` `tag=2.*`
Neovim Version: `nightly`

When you click on the close button of the currently selected tab **while** having multiple buffers open it will close neovim.
(It seems like :bd also does this for some reason, so if this purely a neovim issue let me know and i'll close this issue.)

### What did you expect to happen?

Buttons for the current buffer, will close only the buffer without exiting neovim

### Additional Information

![Issue](https://user-images.githubusercontent.com/33547558/169491528-99e9d674-7055-4ec0-8005-3a59d34656ea.gif)

**Comment by akinsho** [comment]
@MordechaiHadad I think there's a misunderstanding of what that button does, tbh it's a real legacy choice I made right at the beginning to always have that button visible, ideally it should only show when there is more than one tab open. It relates specifically and exclusively to vim tabs and is a means of closing tabpages. If you had more than one tab open it would close the tab. If you only have one tab open it does nothing which is just how vim behaves, that button is basically a copy of the default example for a close button in the tabline.

It is not a button to close neovim. I don't think I would add that, as I can only imagine all the issues that that would invite.

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad I think there's a misunderstanding of what that button does, tbh it's a real legacy choice I made right at the beginning to always have that button visible, ideally it should only show when there is more than one tab open. It relates specifically and exclusively to vim tabs and is a means of closing tabpages. If you had more than one tab open it would close the tab. If you only have one tab open it does nothing which is just how vim behaves, that button is basically a copy of the default example for a close button in the tabline.
> 
> It is not a button to close neovim. I don't think I would add that, as I can only imagine all the issues that that would invite.

Alright fair enough, but it's not the only thing I'm talking about.

If you can see in the GIF, when I open the yabs.lua file and click on this buffer's close button it closes all of neovim and takes me back to my shell.

Hope my message is clearer now.

**Comment by akinsho** [comment]
@MordechaiHadad can you clarify what branch and what commit you are using?

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad can you clarify what branch and what commit you are using?

Yeah sorry for that I'll update it now

**Comment by akinsho** [comment]
Can you try `dev` to see if the issue persists there before I start digging into things, in case it's already been resolved? Also, would be great to have specific reproduction steps. In my case, just hitting the rightmost buffer tab doesn't close neovim.

**Comment by MordechaiHadad** [comment]
> Can you try `dev` to see if the issue persists there before I start digging into things, in case it's already been resolved? Also, would be great to have specific reproduction steps. In my case, just hitting the rightmost buffer tab doesn't close neovim.

Sure give me a minute.
Also the only reproduction steps are simply having 2 or more buffers and click on the close button for the utmost right buffer.
I would have provided my bufferline config but its simply the setup function with no arguments.

Also the issue also happened when i specified `tag=2.*` in packer which is why i switched to the main branch.

**Comment by MordechaiHadad** [comment]
Okay i actually found what is causing this, Ill update the issue.

**Comment by akinsho** [comment]
@MordechaiHadad any info on if this is reproducible in `dev`?

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad any info on if this is reproducible in `dev`?

Yeah it is sorry i forgot to mention it, ill update the issue again

**Comment by akinsho** [comment]
@MordechaiHadad just to clarify since I'm now a bit confused, does neovim close if there are multiple buffers open or only one. Because if there is only one, then that is normal neovim behaviour and not a plugin issue?

**Comment by MordechaiHadad** [comment]
@akinsho I'll try to clarify with an example:
Let's say I have buffers, 1,2 and 3 open.
And my current buffer is 2, let's say I want to close buffer 2 I expect it to close buffer 2, but keep buffers 1 and 3 like every other code editor.
But instead all of neovim closes.

**Comment by akinsho** [comment]
@MordechaiHadad I can't reproduce this locally. On my side, closing buffers does not close neovim, Can you check that you have `set hidden` enabled or provide a minimal init.lua. Is there some specific order that reproduces this? have you changed your bufferline click actions to do something different?

**Comment by MordechaiHadad** [comment]
@akinsho I'll provide a minimal init.lua, just to double check are you sure you closed **only** the buffer you currently out of n buffers?

**Comment by akinsho** [comment]
You mean, did I close my current buffer only to trigger this issue? yep, tried that and didn't see this problem. Tbh I'm inclined to think this is probably configuration or native behaviour as I haven't touched the click logic in like a year

**Comment by MordechaiHadad** [comment]
@akinsho Okay so I have made a minimal [neovim config](https://www.toptal.com/developers/hastebin/avoxuziwof.php) also it seems the issue only occurs when you have a [Trouble](https://github.com/folke/trouble.nvim) window open

**Comment by akinsho** [comment]
@MordechaiHadad so coming back to this issue, can you reproduce it just using the exact same setup but rather than pressing the close button you use `:bdelete` if that does reproduce as you mention in the issue description then this appears to be normal nvim behaviour. `bd` definitely doesn't behave intuitively as people tend to expect, and by default this plugin just uses bd. I can also imagine a situation where trouble has some logic where if it is the last window in a buffer it closes itself, which would mean you use bd which will close the window, then trouble will detect the window was closed, and it is now on its own, and it will close itself which closes nvim

**Comment by MordechaiHadad** [comment]
@akinsho hi! thanks for the response, I think you are correct regarding the trouble situation... but why? it shouldn't really be the last buffer as I only close one buffer and when a trouble window isn't open it works just fine. 

I think its more fit that I'll move this to Trouble's repo since trouble is causing this issue, right?

**Comment by akinsho** [comment]
@MordechaiHadad I think it is an issue with trouble but an understandable one that will be hard to work around because basically the idea would be to stop fullscreen trouble windows from happening which wouldn't look good but short of trying to find another buffer to jump to which is a bit of a faff for that plugin there's a simple close window logic which probably closes nvim. I'd suggest the easiest solution is not to rely on `:bdelete` which is this plugins default and replace it with one of the many bdelete replacement plugins so that the close action call something like `vim-sayonara` or `nvim-bufdelete` etc.

**Comment by MordechaiHadad** [comment]
@akinsho this is quite unfortunate I'll be honest, Do you suggest opening an issue on trouble's repo and referencing this issue?

**Comment by akinsho** [comment]
@MordechaiHadad this is a very old and well known issue with buffer delete in vim, this has been this way for decades at this point, https://github.com/neovim/neovim/issues/2434 is one example of an issue around this dating back to 2015. I think you raising a new issue on nvim without being willing to make a PR is unlikely to go anywhere. I think the vast majority of users who don't like this behaviour just use one of a zillion plugins that solve this issue. I think by default you should install one of these plugins use it and just get on with your day 🤷🏿 

You could raise an issue with trouble but I think the author will be probably have to do down a rabbit hole trying to figure out which buffer to switch to in the case of self closing the window that they probably wont want to. 

In any event I don't think this is something to handle in this plugin though since the behaviour is already configurable by a user.

**Comment by MordechaiHadad** [comment]
@akinsho fair enough kinda sad none that can codes neovim feels like fixing it, but thank you for helping me figure out this rabbit hole!
