### ISSUE TITLE
The file's icon only shows left half in Windows Terminal

### ISSUE THREAD

**Issue by LimbicSys** [akinsho/nvim-bufferline.lua#44]
![屏幕截图 2021-01-23 142118](https://user-images.githubusercontent.com/30319215/105628277-000e7a00-5e77-11eb-8dfa-2c145d92a343.png)
vs code's terminal
![屏幕截图 2021-01-23 142142](https://user-images.githubusercontent.com/30319215/105628278-00a71080-5e77-11eb-8e6d-e88080297dd1.png)
Windows Terminal

I try to change the code to move the white space right before the filename to the position right after the icon. And then the icon shows properly in Windows Terminal. But I am not sure whether it will have influence on other functions.
![图片](https://user-images.githubusercontent.com/30319215/105628600-d22a3500-5e78-11eb-9c01-93562a2f4aec.png)

**Comment by akinsho** [comment]
Hi @LimbicSys, tbh I'm not sure entirely what to do here since this works on both linux and macos, or rather I haven't gotten any issues and I run it in both. I think the issue is more related to how specific terminal emulators handle drawing certain characters as your example show it works in vscode's terminal but not in the windows one.

> I try to change the code to move the white space right before the filename to the position right after the icon

If you got a PR working for you can you raise it for me to have a look. The plugin keeps track of the size of buffer and it's content so changing the content might cause the size to be miscalculated, but it sounds like you've just reshuffled some spaces. Anyway if you PR what work's for you I'll test it to make sure nothing else breaks and if not will merge it.

**Comment by cooper-anderson** [comment]
Yeah, this is an issue with Windows Terminal itself. I'm pretty sure it is because it draws the characters strictly from left to right, but do not quote me on that. There might be some hacky workarounds like using the non-breaking space character `0x00A0`, but I'm not sure that would be applicable here. I was able to use a hack like that when mixing double-width characters and winblend.
