### ISSUE TITLE
tab height and tab styling 

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#53]
how do I increase tab height? also changing tab styling to this : 
![image](https://user-images.githubusercontent.com/59060246/109451160-ce3e9380-7a72-11eb-9f1f-7c017feb47a0.png) didnt find anything about tab styling in the example configs

**Comment by akinsho** [comment]
@siduck76 you can't actually change the tab height in (neo)vim since it's a terminal application all rows are the height of the text based on the font size. Neovim could implement using multiple rows for the tab bar but given the fixed row size constraint I'm not sure that would look right anyway.

Regarding the alternate styling it is in configuration example but it's not really discoverable it's `separator_style = "slant"` I'll add a note about it in the the help docs

**Comment by akinsho** [comment]
Keep in mind with the `slant` style that how it will look will depend on your terminal emulator, some terminal emulators don't do a good job rendering special characters so the triangle characters might look weird. I personally use [`kitty`](https://sw.kovidgoyal.net/kitty/index.html#) which is really great.

**Comment by siduck76** [comment]
I use ST and the triangle characters are invisible after all

**Comment by akinsho** [comment]
No that should be enough try `` in your terminal promt and see what it draws. I don't know anything about ST I assume this means suckless term but I know that usually only the quite new terminal emulators like alacritty and kitty handle all the fancy characters correctly and of those 2 kitty is better at it.

**Comment by siduck76** [comment]
is this that character? 
![image](https://user-images.githubusercontent.com/59060246/109686676-7e61e880-7ba8-11eb-85f0-6a86afef03e3.png)

**Comment by akinsho** [comment]
I can't really tell fro the screen shot @siduck76 the character is `` you just need to paste it into your terminal and see if it shows a triangle. In my terminal it looks like
<img width="425" alt="Screen Shot 2021-03-02 at 17 21 26" src="https://user-images.githubusercontent.com/22454918/109688020-ba328900-7b7b-11eb-912a-711b6984db38.png">

**Comment by siduck76** [comment]
it shows a triangle but converts into an inverted triangle if I press space 

https://user-images.githubusercontent.com/59060246/109800953-d8fc5280-7c43-11eb-9b11-d5b181a16a62.mp4

**Comment by akinsho** [comment]
@siduck76 this seems to be in the realm of terminal emulator behaviour I can't really do anything about how a specific terminal emulator handles certain characters. Maybe you can file a bug upstream so it can be fixed there, I've had to do that in the past with how kitty was handling some of the box characters this plugin uses.

Meanwhile I will clarify in the docs that the `slant` style has only really been tested with `kitty` and support will depend entirely on the specific terminal emulator someone uses.

**Comment by siduck76** [comment]
ah I see , btw can you add rounded corners to the tabs? 
![image](https://user-images.githubusercontent.com/59060246/110130104-af335f00-7dee-11eb-89bc-a44bb6f9a41f.png)

**Comment by akinsho** [comment]
@siduck76 I'm not sure how I would do that? do you know of an ASCII character like the one I posted that has round corners? it would need to be filled on one side for that to work. That's how all the custom styles work they need matching characters that are partially filled since neovim can only just draw existing characters

**Comment by siduck76** [comment]
yep you can use the ones in powerline fonts , something like this https://github.com/datwaft/bubbly.nvim

**Comment by akinsho** [comment]
Oh I didn't realise that's what you have in mind. I don't really like the look of those since it doesn't really match the aesthetic I'm going for. You can add that in your own config but using `separator_style = {'<left-char>', '<right-char>'}`

**Comment by akinsho** [comment]
I'm going to close this out @siduck76 since I think you can achieve the look you'd like in a few different ways either via swapping terminal emulator, submitting an upstream issue if you want to stick with your own, or by adding in your on separators.

NOTE: not all separator chars will work, it will depend on how the character is filled. As I mentioned in the README though I'm pretty opinionated on what I will add to the plugin itself, the general idea is to mirror Doom Emacs/ GUI editors so won't add the type of styles that you wouldn't see in one of those.

**Comment by siduck76** [comment]
> separator_style = {'<left-char>', '<right-char>'}

![image](https://user-images.githubusercontent.com/59060246/110138515-11dd2880-7df8-11eb-848e-2588a3cf478f.png)
is this right?

**Comment by siduck76** [comment]
st is fine with chars , no problem with that. I think my bufferline config's messed up https://hatebin.com/wbtczwjwhs

**Comment by akinsho** [comment]
Yeah your highlights should all be within the highlights table and I'm not sure where `comment_fg` etc. is defined. Have a close read of the example in the README or the help docs that should show you what's wrong with the table. Can't debug anymore atm as I'm at work

**Comment by towry** [comment]
Remember to disable the `transparent` mode in your colorscheme setting.

If you have `transparent` mode on, it will show up like this:

![截屏2022-11-30 10 20 14](https://user-images.githubusercontent.com/8279858/204698628-6a44b253-3460-45a5-9d7d-fd833304b7b1.png)
