### ISSUE TITLE
[Bug]: colors of inactive tabs are wrong

### ISSUE THREAD

**Issue by pogopaule** [akinsho/nvim-bufferline.lua#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I don't know when this started, but yesterday I noticed this strange color bug for inactive tabs.

![image](https://user-images.githubusercontent.com/576949/205989014-0baa033d-6c69-42da-affa-f366dd739456.png)

### What did you expect to happen?

Correct colors for inactive tabs, like e.g. as in the screenshots in the README.md.

### Config

https://github.com/pogopaule/dotfiles/blob/nix/nvim/lua/pogopaule/plugins.lua#L178-L189

### Additional Information

...

**Comment by akinsho** [comment]
@pogopaule apologies if this comes across as rude but in order to make this plugin more maintainable for me I don't get involved in debugging individual user configs and issues with highlighting. I see this issue often and 99% of them are due to configuration related problems or using the wrong highlight groups. I'm going to close this out because I *know* that those groups can be configured if using the correct settings. I **cannot spare the time to investigate each users configuration** please keep in mind I get dozens of issues like this.

**Comment by MrRoiz** [comment]
@pogopaule did you find a solution for this?

**Comment by pogopaule** [comment]
@MrRoiz No not yet. The bug has become flaky somehow. Sometimes it is there and when I reopen neovim it is gone, and so on...

Why are you asking? Do you have the same problem? If I find a solution I'll post it here.

**Comment by MrRoiz** [comment]
@pogopaule I just found the issue for my case, I'm using Tmux and it was not supporting italic or bold fonts, I had to add this in my tmux conf

```bash
set -g default-terminal "tmux-256color"
```

Idk if this is your case, but hope it works for you bro!
