### ISSUE TITLE
Is there a way to hide buffers and show only tab pages ?

### ISSUE THREAD

**Issue by luisiacc** [akinsho/nvim-bufferline.lua#64]
Is there a way to hide buffers and show only tab pages ?

**Comment by akinsho** [comment]
@luisiacc do you mean just the minimal tab indicators or show tabs in the same way buffers are shown, tbh in either case I don't think I'll implement this. It's quite a different use case from what this plugin is intended for. If someone were to think up a way of implementing this that didn't disrupt the main use case of this plugin then I'd review since I'm not totally against the idea, but it's a bit too much work for something I'd never use.

**Comment by luisiacc** [comment]
I mean just the minimal tab indicators, and don't show buffers as tabs.

**Comment by akinsho** [comment]
@luisiacc this week alone I've added ability to hide tabs as well as the close button, but think I have to draw the line somewhere. I think if you just want to see tab indicators, vim will do this natively without a plugin and very minimal tweaking. I don't think I'm going to add an option to hide all buffers since that sort of defeats the point of this plugin

**Comment by akinsho** [comment]
I'm going to close this out now since I don't think there's much else to add.
