### ISSUE TITLE
Different icon / highlight for active  buffer_close_icon 

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#65]
Is there any way I could change the icon for the active buffer's close icon? or at least make it colored different like red colored close icon only for the active buffer's tab

![image](https://user-images.githubusercontent.com/59060246/111978774-4eb05b80-8b2a-11eb-8a77-95584ee7cca1.png)

**Comment by akinsho** [comment]
@siduck76 not at the moment, highlighting each icon is not as straightforward as you would think in neovim since it uses this arcane DSL and highlights don't behave the way I'd like.

Anyway it is possible/not *too* hard to do. The close icon is added [here](https://github.com/akinsho/nvim-bufferline.lua/blob/c387d2cdd7ae946726d2de29a6ac79b820bf4ddf/lua/bufferline.lua#L311) it would need to have a highlight for it defined in the config and given a default. Maybe the default is nothing so it doesn't change for anyone who didn't/doesn't want this change. 

The change would look something like
```lua
local function close_icon(buf_id, preferences)
  local buffer_close_icon = options.buffer_close_icon
  local symbol = buffer_close_icon .. padding
  local size = strwidth(symbol)
  return  preferences.highlights.close_icon .. "%" .. buf_id .. "@nvim_bufferline#handle_close_buffer@" .. symbol, size
end
```

Since neovim doesn't inherit background highlights you would need to create `close_icon_active`, `close_icon_visible` and `close_icon` highlights and apply each depending on the buffers state. Similar to [here](https://github.com/akinsho/nvim-bufferline.lua/blob/c387d2cdd7ae946726d2de29a6ac79b820bf4ddf/lua/bufferline.lua#L106)

I'm trying to manage my time a little better so I'm not spending all my time maintaining the plugins I made, so if anyone else wanted to pick this up I can add some more tips. Otherwise I'll get to this eventually but not gonna rush as I'm already working on a few other things 😓 .

**Comment by siduck76** [comment]
oh its fine then , I'll just use the way it is :)

**Comment by akinsho** [comment]
@siduck76 it's worth keeping open for a while anyway I might get to it in a bit/someone else might be up for adding the change. I'll leave it here for a couple of weeks and see if I get round to it or someone else does

**Comment by akinsho** [comment]
I've decided to close this since I personally probably won't implement this myself and no one else has stepped forward to do it. This could maybe be revisited in the future. I'd like to make the close icons hide unless hovering and there is a neovim issue (several years old) to add hover events so if that ever gets added 😆

**Comment by siduck76** [comment]
@akinsho No worries! after some thought I think that feature was actually useless XD , sorry for creating its issue on the repo!
