### ISSUE TITLE
Unique buffer names does not work

### ISSUE THREAD

**Issue by ahmadov** [akinsho/nvim-bufferline.lua#71]
I'm expecting both `init.lua` files are prefixed with folder names in the buffers but apparently, they are not.

Do I need to enable it somehow? I didn't find it in the docs.

Screenshot:
![image](https://user-images.githubusercontent.com/7130712/113319524-cc861b00-9311-11eb-8aa7-b434464b8a0b.png)

**Comment by akinsho** [comment]
@ahmadov this is a screenshot me using this taken, just now. So I don't believe there's a regression or anything.
![image](https://user-images.githubusercontent.com/22454918/113326804-0fe08980-9312-11eb-9426-85029e0775fd.png)

I need more information about the each file specifically to know why you aren't seeing the deduplication. What are the full paths for both files? if the files are exactly the same then it will not be able to deduplicate because they are literally indistinguishable, since that's unlikely another possibility is that the file paths are similar and it is within a too nested dir structure.

**Comment by ahmadov** [comment]
I can confirm that it works! Thanks!
