### ISSUE TITLE
[Bug] Hello, If I edit a file with name patter `number-chineseword`, neovim will crush.

### ISSUE THREAD

**Issue by fgheng** [akinsho/nvim-bufferline.lua#81]
If I use nvim-bufferline.lua, and edit a file like `516-最长回文子序列.cc`, neovim crushed:
![image](https://user-images.githubusercontent.com/50551377/114644077-6c2bac00-9d09-11eb-95d4-e18c5cd1e5e9.png)
But If I not use nvim-bufferline.lua, neovim works well.

If I edit a file without `-` like `516最长回文.cc` neovim also works well.

**Comment by akinsho** [comment]
@fgheng thanks for raising this issue I was completely unaware this happened. I think this is best raised upstream in neovim itself though since something causing the program to segfault needs to be resolved there. The screenshot you sent seems to give a very clear signal to where this is happening so maybe this can be resolved. On my end I'll experiment a little and try and figure out exactly within this plugin might be triggering the issue and post any updates in the issue you raise in nvim

**Comment by fgheng** [comment]
thank you very much.

**Comment by akinsho** [comment]
@fgheng when you raise the issue can you please post the link here or reference this issue from there so I can keep track of what's happening

**Comment by akinsho** [comment]
The upstream part of this bug is not resolved, and was not reported the OP didn't nor have I had the time, but it was due to trying to truncate multibyte characters by byte which this plugin now handles better anyway
