### ISSUE TITLE
Bug: attempt to call field 'is_test' (a nil value)

### ISSUE THREAD

**Issue by bamzi** [akinsho/nvim-bufferline.lua#83]
On the latest Neovim nightly and with the latest version of the Bufferline, when starting a new session, presented with the following error:

```
E5108: Error executing lua ...nvim/plugged/nvim-bufferline.lua/lua/bufferline.lua:45: attempt to call field 'is_test' (a nil value)
```

The error might be as a result of code changes in the past 3 or so days.

**Comment by akinsho** [comment]
@bamzi I'm not sure how what you're seeing is possible tbh, I did add a method called `is_test` to my `utils.lua` but they were added in the same PR so that function should definitely exist.

https://github.com/akinsho/nvim-bufferline.lua/blob/78ffd345d079246738ea06b04f58ad53503f48e2/lua/bufferline/utils.lua#L6

 Do you still see the issue if you run a minimal `init.lua` e.g. `nvim -u <path-to-minimal>` and then just load this plugin on it's own without the rest of your config

**Comment by bamzi** [comment]
Culprit was barbar.nvim plugin .. should've disabled it before trying this plugin
