### ISSUE TITLE
Option to ensure that the terminal buffer won’t be hidden 

### ISSUE THREAD

**Issue by brymer-meneses** [akinsho/nvim-bufferline.lua#86]
The terminal buffer tab would become hidden if I switched to another buffer. Is there any way to prevent it from doing so?

**Comment by akinsho** [comment]
Hi @brymer-meneses,

I'm not sure from the description you have given what exactly you mean. Depending on how you are using the plugin i.e. if using splits then the only way that a terminal is removed from the current layout is if a user either toggles it closed, closes the window or navigates to another buffer from within the terminal window.

When you say stop it from being hidden do you mean i.e. not using vim's `:h hidden` property because that is the crux of this plugin and it won't work *at all* without that.

I suspect though that you don't mean that and maybe you mean you want the toggle term to stay open in which case you can do this by 1.) don't close it using `ToggleTerm`, 2.) Don't navigate to other buffers inside the terminal window

**Comment by akinsho** [comment]
Okay so this plugin doesn't control the visibility of your buffers at all *unless* you are using the filter feature which I'm sure you'd know if you were. All this plugin does is ask vim for a list of all your buffers add filters that based on which ones are set by vim/your config as `buflisted`.

In all likelihood your terminals are not set as `buflisted` either by default or by configuration in vim. In either case this isn't being controlled in this plugin.

**Comment by akinsho** [comment]
![image](https://user-images.githubusercontent.com/22454918/116880585-1700fd00-ac1a-11eb-9318-07150038ca6c.png)

Here's an example where I opened a terminal using `sp | term` and then navigated away from it, as you can see the terminal is still showing up in bufferline since it is not `buflisted=false` so I think whatever plugin you are using or somewhere in your config terminals are being set to `nobuflisted`

**Comment by brymer-meneses** [comment]
For some reason when I execute `:terminal' and move to another buffer it goes missing. However when I use `:sp | term` (which I didn't know existed) worked as expected! TY!

**Comment by akinsho** [comment]
One thing to check is that you have set `set hidden` in your vim otherwise when you navigate away from a terminal it will be deleted.
