### ISSUE TITLE
bufferline length

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#89]
is It possible to change bufferline length ? I dont want it 100% and get mixed with NvimTree (file tree on the left)

![image](https://user-images.githubusercontent.com/59060246/117336279-a5df7500-aeb9-11eb-9e00-511104144c6c.png)

I want it to get separated from the NvimTree , something like this 

![image](https://user-images.githubusercontent.com/59060246/117340107-2bfdba80-aebe-11eb-8275-576396680742.png)

**Comment by akinsho** [comment]
@siduck76 someone else asked a similar question in another issue, the short answer is that it isn't very easy. Neovim doesn't natively provide functionality to do that sort of thing since an explorer is just a random window in nvim rather than in vscode where it is a specific element in the view.

Somehow bufferline would have basically pad the left or right hand side of the tabline with spaces corresponding to the size of `x` window, it would also then have to provide some way to apply a custom highlight to this padding if you wanted it to look like the window above.

It wouldn't be as simple as just taking a length number from a user since there are a bunch of edge cases where it wouldn't work for other people e.g. what happens when the window is closed, what happens if the user provides a static window width but they open things on a monitor that is too big or small.

Basically if nvim allowed tablines per window that would be a very easy problem to solve and might even open up some other potential things like buffers grouped to windows.

For now though it would have to a highlighted space hack, in which case how would it know when the space should be there and when it shouldn't, could listen for a specific window and redraw if that window opened or closed 🤔 .

I'm all for eye candy and don't think it's a bad idea (visually) but the implementation would be hacky so I'm not thrilled about what it would look like. If someone wanted to submit a PR I wouldn't be opposed otherwise this will have to wait till some weekend when I have time/can think of a good solution.

I think it's worth noting that there is a limit on how far a TUI text editor can go in terms of trying to mirror a GUI like vscode, not to say that this is that limit. it would just be better if this could work natively somehow 🤷🏾

**Comment by siduck76** [comment]
cool , I would want to do the highlighting hack :D

**Comment by siduck76** [comment]
@akinsho I think it would be better to add a little block (with custom highlight )  in front of the bufferline so it would the way I want . something like this 
![image](https://user-images.githubusercontent.com/59060246/117340267-55b6e180-aebe-11eb-9f0b-3bc33344331e.png)  , so I could add some text like "File explorer" in that block too and make its color look the same as Nvimtree's bg.

**Comment by akinsho** [comment]
😅  @siduck76 the feature doesn't even exist but is already becoming more complex.

The solution will need some thinking over it won't be enough to just randomly add some padding or text to the left or right of the bufferline and pass in some config values. A solution would need to look at the layout of the window, I don't want to integrate this specifically with plugins since that will just cause an endless series of requests to support plugin `x`.

The user would have to be able to give a clear way to identify their window of choice e.g. `winid` or `filetype` etc. then that would have to be checked versus the current window layout to find out if the window is open in a vertical split in the current tab.

If not then do nothing. If it is then you'd have to get the width of that window and the side i.e. left or right as in leftmost or right most if it isn't on the extreme edge then it shouldn't trigger padding since that would be pointless.

Then the padding could be applied to the correct side with the right highlight as well, then would need a way to make sure it gets updated correctly though when the layout changes.

A workaround you can try in your own config for now is some other users are using the global `nvim_bufferline` function that is what this plugin uses for the value of `&tabline` directly e.g.

```lua
function _G.custom_tabline()
 local bufferline = _G.nvim_bufferline()
 return hl_group .. string.rep(window_size) .. bufferline
end
set tabline=%!v:lua.custom_tabline()
```

**Comment by akinsho** [comment]
Actually just had a quick try and seems like it might not be as bad as I thought

![image](https://user-images.githubusercontent.com/22454918/117343742-8128d480-ae9c-11eb-97b2-32befb4b5b2d.png)

But I'm working on some other plugins atm so will only be able to look at this when I get time. As always if someone wanted to pitch in and *help* that would be great, I can push what I've got into a Draft PR if you want to have a go at tidying it up @siduck76

**Comment by siduck76** [comment]
@akinsho my lua knowledge is basic , sorry I cant help with the code :c . How did you get that empty block on the left btw?

**Comment by akinsho** [comment]
@siduck76 you can already achieve something close to this using the snippet I posted above
> function _G.custom_tabline()
 local bufferline = _G.nvim_bufferline()
 return hl_group .. string.rep(window_size) .. bufferline
end
set tabline=%!v:lua.custom_tabline()

You would need to figure out some of the details to make the snippet work in your case, if you are not comfortable/cannot do that you will have to wait till I have time to implement this fully

**Comment by siduck76** [comment]
I'll wait until its implemented :)
