### ISSUE TITLE
How can I add current cwd as offset's text?

### ISSUE THREAD

**Issue by siduck** [akinsho/nvim-bufferline.lua#94]
fnamemodify(getcwd(), ':t') might help

**Comment by akinsho** [comment]
@siduck76 this is more about `lua`/`vimscript` than this plugin since it will take whatever text you give it 🤷🏾 . The example you have above looks like it might work you just need to use that in `lua` using `vim.fn.fnamemodify(<args>)`

**Comment by siduck76** [comment]
@akinsho  The offset shows null 
 
local current_dir = vim.fn.fnamemodify(getcwd, ":t")
offsets = {{filetype = "NvimTree", text = current_dir}},

![image](https://user-images.githubusercontent.com/59060246/117706205-a2662980-b1ea-11eb-9709-95638be210f5.png)

**Comment by akinsho** [comment]
You can't left align the offset for the time being in order to change the highlight group you need to specify a `highlight = "<my-hl-group-name>"` see #92 for an example of how someone else solved it

**Comment by siduck76** [comment]
Im confused , that guy used a highlight group "File Explorer"  but there isnt highlight group for offset

**Comment by akinsho** [comment]
@siduck76 you have to either choose an existing highlight group. You can see what those are by running `:highlight<CR>` or you have to 1.) Create a highlight group 2. ) specify the highlight group in the highlight key in the table. You can learn more about creating highlight groups using `:h highlight`

**Comment by siduck76** [comment]
@akinsho  I didnt wanted to create an issue for this sillly question , what are tabs in bufferline?

**Comment by akinsho** [comment]
@siduck76 this is kind of a big question or rather the answer is a bit long the best detailed explanation is in 
`:help tabpage`. Below is from that help page.
A tab isn't a "workspace" a tab is away of arranging buffer into a different layout of window. Say you have one window you split into two. You might want to have these side by side but just for 20mins you want to focus on the left split. Rather than closing it you can move the left split to a new tab. TLDR: a tab is an arrangement of **windows** tabs don't care about specific buffers and buffers aren't specific to tabs either

> 1. Introduction						*tab-page-intro*

> A tab page holds one or more windows.  You can easily switch between tab
pages, so that you have several collections of windows to work on different
things.

> Usually you will see a list of labels at the top of the Vim window, one for
each tab page.  With the mouse you can click on the label to jump to that tab
page.  There are other ways to move between tab pages, see below.

> Most commands work only in the current tab page.  That includes the |CTRL-W|
commands, |:windo|, |:all| and |:ball| (when not using the |:tab| modifier).
The commands that are aware of other tab pages than the current one are
mentioned below.

> Tabs are also a nice way to edit a buffer temporarily without changing the
current window layout.  Open a new tab page, do whatever you want to do and
close the tab page.
