### ISSUE TITLE
Error while calling lua chunk: loop or previous error loading module 'bufferline'

### ISSUE THREAD

**Issue by foodornt** [akinsho/nvim-bufferline.lua#95]
Calling `require('bufferline').setup({})` causes the issue

any idea what's going on?

**Comment by akinsho** [comment]
@foodornt I'll need more information to help you out. Calling it as you have done there doesn't throw any errors on my end. It should just start `bufferline` with the default options. Have you tried this out with a minimal `init.vim` i.e. *no other plugins* or settings just this plugin and seeing if it throws this error. If not then add things back one at at time to see what triggers it.

FWIW this plugin cannot be used if something like `barbar` is also installed since they both declare a `lua` module called `bufferline`

**Comment by foodornt** [comment]
Sure, here's a MWE

```lua
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use {'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons', opt=true}
end)

require('bufferline').setup({})
```

gives same error

**Comment by akinsho** [comment]
@foodornt in the example above, `bufferline` is set as an `opt` plugin which means it won't be loaded by packer or vim so the module won't be available, which is why it errors. You need to remove the `opt = true` from your packer spec

**Comment by foodornt** [comment]
I tried so many things, I removed opt and invoked `:PackerStatus` but when I go to the plugin and press enter it says: opt=true (but it's loaded)

I tried to set opt to false, but same thing, nothing happens

I have all my plugins set to opt=true and none of them has this issue though

**Comment by akinsho** [comment]
@foodornt if a plugin has some other trigger other than opt then it will be loaded but in bufferlines case where you specified the opt nothing will trigger loading. If a plugin is actually it without triggers it cannot be loaded. 

In your case did you also make sure to run packer compile then packer sync and reload neovim?

**Comment by foodornt** [comment]
Yeah I ran everything, clean update sync compile and repeated that once again but nothing fixes the error.

is there a way to show the full error and which line is causing it?

**Comment by akinsho** [comment]
@foodornt I'm in mobile atm so can't help really but that error is to do with an issue loading the module I can't reproduce that in a minimal init.vim try to make sure your packer compiled file isn't loaded and that you are definitely not loading other vim sessions

**Comment by akinsho** [comment]
@foodornt I actually have been on mobile so didn't notice what the issue is. It's actually that your use of `packer` is incorrect. You can't require the plugin straight after calling packer startup because it doesn't work like that. you need to do
```lua
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use {'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons', config = function()
		require('bufferline').setup({})
	end}
end)
```
Packer doesn't load plugins immediately it loads them after reading your init.vim so you can only call things like setup inside it's config function. You can read about it in Packer's README but it isn't an issue with this plugin

**Comment by foodornt** [comment]
Thank you for the help akinsho, but I still couldn't get it right, even using the config parameter

I added this to my config, saved the file and exited, came back to run PackerCompile, and it would give me the same error 😞

I'm pretty sure the error is due to my wrong usage of packer.nvim, I'll keep trying different solutions and hopefully I can get things right

if you use neovim, I'd like to check your dotfiles (I checked your dotfiles repo but you only have .vimrc, and bufferline isn't used there)

**Comment by akinsho** [comment]
My neovim config is in that repo in the .config directory so it can be symlinked to the home sir just search init.lua in that directory

**Comment by foodornt** [comment]
Oh no, I wasted 9 hours on this, the error was caused by the file called bufferline.lua that was in my lua folder

I guess not only my time was wasted, apologies, akinsho 😅
